id: ID37D8CFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:43:08+00:00'
last_modified: '2022-06-08T11:48:42.666120+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19144
  title: ཚད་མའི་བསྟན་བཅོས་རིག་པ་ལ་འཇུག་པ་ཞེས་བྱ་བའི་འགྲེལ་པ་རིགས་ལམ་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    ABFA:
      image_group_id: I8LS19146
      title: ''
      total_pages: 216
      order: 1
      base_file: ABFA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
